### ISSUE TITLE
Consider using Oauth2Client module

### ISSUE THREAD

**Issue by FatherShawn** [iagsdc/phpmailer_gmail_oauth2#1]
Hi!  I saw your post on [drupal.org](https://www.drupal.org/project/smtp/issues/3102055#comment-15572801).  I thought I'd bring [Oauth2Client ](https://www.drupal.org/project/oauth2_client) to your attention.  It could simplify your code here quite a bit as it is a plugin based general Oauth2 client manager which handles all the Oauth2 interactions and token management.  It's a developer module for creating custom plugins tailored to the Oauth2 configuration of an external system. It includes some [example plugins](https://git.drupalcode.org/project/oauth2_client/-/tree/4.1.x/examples/oauth2_client_example_plugins?ref_type=heads). 

It's designed to use any League AbstractProvider so I think it would easily offload good deal of your maintenance here.

**Comment by iagsdc** [comment]
Thanks for pointing that out.  I’ll take a look.

**Comment by iagsdc** [comment]
I've added a new repository (oauth2_client_gmail_plugin) containing a plugin designed to work with Oauth2Client.  It still needs a README to document the setup; I'll add that in a day or two.

**Comment by iagsdc** [comment]
See repository iagsdc/oauth2_client_gmail_plugin.

**Comment by iagsdc** [comment]
Shawn,

You may have seen I filed a Feature Request on the Drupal OAuth2 Client page.  

I can get a gmail  OAuth2 Client plugin to work, but only if I store the gmail address inDescription.  Various flavors of the OAuth2 Client form allow for username and password, but don’t store the values.  Gmail address is needed every time an email is sent.

Fred
